spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goldnexus
    username: root
    password: 05240314lzx
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: nihao123321
  expiration: 86400000
